# Documentation Site Settings
title: "Aiman Elyas | DevOps Project"
description: "Documentation for my final DevOps Bootcamp project."

# Theme Settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Formatting Fixes
markdown: GFM
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge  # Makes your code blocks colorful